# Generated by Django 5.0.1 on 2024-02-01 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helpdesk.ticketcategory'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(default='Normal', max_length=50),
        ),
    ]
