# Generated by Django 5.0.1 on 2024-02-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_alter_ticket_assigned_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketattachment',
            name='file',
            field=models.FileField(upload_to='attachments/'),
        ),
    ]
