# Generated by Django 5.0.1 on 2024-02-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0004_alter_ticketattachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
