# Generated by Django 5.0.1 on 2024-02-02 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0005_ticket_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='ticketremark',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
