# Generated by Django 5.0.6 on 2024-06-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helpdesk", "0007_alter_ticketremark_ticket_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("subject", models.TextField()),
                ("email", models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name="TicketStatus",
        ),
    ]
